/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTransaksiRouteImport } from './routes/_app/transaksi'
import { Route as AppRiwayatRouteImport } from './routes/_app/riwayat'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppKoleksiRouteImport } from './routes/_app/koleksi'
import { Route as AppKeranjangRouteImport } from './routes/_app/keranjang'
import { Route as AppFavoritRouteImport } from './routes/_app/favorit'
import { Route as AppEventRouteImport } from './routes/_app/event'
import { Route as AppTokoIndexRouteImport } from './routes/_app/toko.index'
import { Route as AppTokoVerifikasiRouteImport } from './routes/_app/toko.verifikasi'
import { Route as AppTokoUploadRouteImport } from './routes/_app/toko.upload'
import { Route as AppTokoRiwayatRouteImport } from './routes/_app/toko.riwayat'
import { Route as AppTokoPengembalianRouteImport } from './routes/_app/toko.pengembalian'
import { Route as AppTokoBukuRouteImport } from './routes/_app/toko.buku'
import { Route as AppTokoIdRouteImport } from './routes/_app/toko.$id'
import { Route as AppCheckoutIdRouteImport } from './routes/_app/checkout.$id'
import { Route as AppBukuIdRouteImport } from './routes/_app/buku.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminTokoRouteImport } from './routes/_app/admin.toko'
import { Route as AppAdminPencairanRouteImport } from './routes/_app/admin.pencairan'
import { Route as AppAdminKatalogRouteImport } from './routes/_app/admin.katalog'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin.dashboard'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransaksiRoute = AppTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => AppRoute,
} as any)
const AppRiwayatRoute = AppRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppKoleksiRoute = AppKoleksiRouteImport.update({
  id: '/koleksi',
  path: '/koleksi',
  getParentRoute: () => AppRoute,
} as any)
const AppKeranjangRoute = AppKeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritRoute = AppFavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => AppRoute,
} as any)
const AppEventRoute = AppEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AppRoute,
} as any)
const AppTokoIndexRoute = AppTokoIndexRouteImport.update({
  id: '/toko/',
  path: '/toko/',
  getParentRoute: () => AppRoute,
} as any)
const AppTokoVerifikasiRoute = AppTokoVerifikasiRouteImport.update({
  id: '/toko/verifikasi',
  path: '/toko/verifikasi',
  getParentRoute: () => AppRoute,
} as any)
const AppTokoUploadRoute = AppTokoUploadRouteImport.update({
  id: '/toko/upload',
  path: '/toko/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppTokoRiwayatRoute = AppTokoRiwayatRouteImport.update({
  id: '/toko/riwayat',
  path: '/toko/riwayat',
  getParentRoute: () => AppRoute,
} as any)
const AppTokoPengembalianRoute = AppTokoPengembalianRouteImport.update({
  id: '/toko/pengembalian',
  path: '/toko/pengembalian',
  getParentRoute: () => AppRoute,
} as any)
const AppTokoBukuRoute = AppTokoBukuRouteImport.update({
  id: '/toko/buku',
  path: '/toko/buku',
  getParentRoute: () => AppRoute,
} as any)
const AppTokoIdRoute = AppTokoIdRouteImport.update({
  id: '/toko/$id',
  path: '/toko/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutIdRoute = AppCheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBukuIdRoute = AppBukuIdRouteImport.update({
  id: '/buku/$id',
  path: '/buku/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTokoRoute = AppAdminTokoRouteImport.update({
  id: '/admin/toko',
  path: '/admin/toko',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPencairanRoute = AppAdminPencairanRouteImport.update({
  id: '/admin/pencairan',
  path: '/admin/pencairan',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminKatalogRoute = AppAdminKatalogRouteImport.update({
  id: '/admin/katalog',
  path: '/admin/katalog',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/event': typeof AppEventRoute
  '/favorit': typeof AppFavoritRoute
  '/keranjang': typeof AppKeranjangRoute
  '/koleksi': typeof AppKoleksiRoute
  '/profile': typeof AppProfileRoute
  '/riwayat': typeof AppRiwayatRoute
  '/transaksi': typeof AppTransaksiRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/admin/pencairan': typeof AppAdminPencairanRoute
  '/admin/toko': typeof AppAdminTokoRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/buku/$id': typeof AppBukuIdRoute
  '/checkout/$id': typeof AppCheckoutIdRoute
  '/toko/$id': typeof AppTokoIdRoute
  '/toko/buku': typeof AppTokoBukuRoute
  '/toko/pengembalian': typeof AppTokoPengembalianRoute
  '/toko/riwayat': typeof AppTokoRiwayatRoute
  '/toko/upload': typeof AppTokoUploadRoute
  '/toko/verifikasi': typeof AppTokoVerifikasiRoute
  '/toko/': typeof AppTokoIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/event': typeof AppEventRoute
  '/favorit': typeof AppFavoritRoute
  '/keranjang': typeof AppKeranjangRoute
  '/koleksi': typeof AppKoleksiRoute
  '/profile': typeof AppProfileRoute
  '/riwayat': typeof AppRiwayatRoute
  '/transaksi': typeof AppTransaksiRoute
  '/': typeof AppIndexRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/katalog': typeof AppAdminKatalogRoute
  '/admin/pencairan': typeof AppAdminPencairanRoute
  '/admin/toko': typeof AppAdminTokoRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/buku/$id': typeof AppBukuIdRoute
  '/checkout/$id': typeof AppCheckoutIdRoute
  '/toko/$id': typeof AppTokoIdRoute
  '/toko/buku': typeof AppTokoBukuRoute
  '/toko/pengembalian': typeof AppTokoPengembalianRoute
  '/toko/riwayat': typeof AppTokoRiwayatRoute
  '/toko/upload': typeof AppTokoUploadRoute
  '/toko/verifikasi': typeof AppTokoVerifikasiRoute
  '/toko': typeof AppTokoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/event': typeof AppEventRoute
  '/_app/favorit': typeof AppFavoritRoute
  '/_app/keranjang': typeof AppKeranjangRoute
  '/_app/koleksi': typeof AppKoleksiRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/riwayat': typeof AppRiwayatRoute
  '/_app/transaksi': typeof AppTransaksiRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/katalog': typeof AppAdminKatalogRoute
  '/_app/admin/pencairan': typeof AppAdminPencairanRoute
  '/_app/admin/toko': typeof AppAdminTokoRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/buku/$id': typeof AppBukuIdRoute
  '/_app/checkout/$id': typeof AppCheckoutIdRoute
  '/_app/toko/$id': typeof AppTokoIdRoute
  '/_app/toko/buku': typeof AppTokoBukuRoute
  '/_app/toko/pengembalian': typeof AppTokoPengembalianRoute
  '/_app/toko/riwayat': typeof AppTokoRiwayatRoute
  '/_app/toko/upload': typeof AppTokoUploadRoute
  '/_app/toko/verifikasi': typeof AppTokoVerifikasiRoute
  '/_app/toko/': typeof AppTokoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/event'
    | '/favorit'
    | '/keranjang'
    | '/koleksi'
    | '/profile'
    | '/riwayat'
    | '/transaksi'
    | '/admin/dashboard'
    | '/admin/katalog'
    | '/admin/pencairan'
    | '/admin/toko'
    | '/admin/users'
    | '/buku/$id'
    | '/checkout/$id'
    | '/toko/$id'
    | '/toko/buku'
    | '/toko/pengembalian'
    | '/toko/riwayat'
    | '/toko/upload'
    | '/toko/verifikasi'
    | '/toko/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/event'
    | '/favorit'
    | '/keranjang'
    | '/koleksi'
    | '/profile'
    | '/riwayat'
    | '/transaksi'
    | '/'
    | '/admin/dashboard'
    | '/admin/katalog'
    | '/admin/pencairan'
    | '/admin/toko'
    | '/admin/users'
    | '/buku/$id'
    | '/checkout/$id'
    | '/toko/$id'
    | '/toko/buku'
    | '/toko/pengembalian'
    | '/toko/riwayat'
    | '/toko/upload'
    | '/toko/verifikasi'
    | '/toko'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/event'
    | '/_app/favorit'
    | '/_app/keranjang'
    | '/_app/koleksi'
    | '/_app/profile'
    | '/_app/riwayat'
    | '/_app/transaksi'
    | '/_app/'
    | '/_app/admin/dashboard'
    | '/_app/admin/katalog'
    | '/_app/admin/pencairan'
    | '/_app/admin/toko'
    | '/_app/admin/users'
    | '/_app/buku/$id'
    | '/_app/checkout/$id'
    | '/_app/toko/$id'
    | '/_app/toko/buku'
    | '/_app/toko/pengembalian'
    | '/_app/toko/riwayat'
    | '/_app/toko/upload'
    | '/_app/toko/verifikasi'
    | '/_app/toko/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transaksi': {
      id: '/_app/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof AppTransaksiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riwayat': {
      id: '/_app/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AppRiwayatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/koleksi': {
      id: '/_app/koleksi'
      path: '/koleksi'
      fullPath: '/koleksi'
      preLoaderRoute: typeof AppKoleksiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keranjang': {
      id: '/_app/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof AppKeranjangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorit': {
      id: '/_app/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof AppFavoritRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event': {
      id: '/_app/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AppEventRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toko/': {
      id: '/_app/toko/'
      path: '/toko'
      fullPath: '/toko/'
      preLoaderRoute: typeof AppTokoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toko/verifikasi': {
      id: '/_app/toko/verifikasi'
      path: '/toko/verifikasi'
      fullPath: '/toko/verifikasi'
      preLoaderRoute: typeof AppTokoVerifikasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toko/upload': {
      id: '/_app/toko/upload'
      path: '/toko/upload'
      fullPath: '/toko/upload'
      preLoaderRoute: typeof AppTokoUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toko/riwayat': {
      id: '/_app/toko/riwayat'
      path: '/toko/riwayat'
      fullPath: '/toko/riwayat'
      preLoaderRoute: typeof AppTokoRiwayatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toko/pengembalian': {
      id: '/_app/toko/pengembalian'
      path: '/toko/pengembalian'
      fullPath: '/toko/pengembalian'
      preLoaderRoute: typeof AppTokoPengembalianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toko/buku': {
      id: '/_app/toko/buku'
      path: '/toko/buku'
      fullPath: '/toko/buku'
      preLoaderRoute: typeof AppTokoBukuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toko/$id': {
      id: '/_app/toko/$id'
      path: '/toko/$id'
      fullPath: '/toko/$id'
      preLoaderRoute: typeof AppTokoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout/$id': {
      id: '/_app/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof AppCheckoutIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buku/$id': {
      id: '/_app/buku/$id'
      path: '/buku/$id'
      fullPath: '/buku/$id'
      preLoaderRoute: typeof AppBukuIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/toko': {
      id: '/_app/admin/toko'
      path: '/admin/toko'
      fullPath: '/admin/toko'
      preLoaderRoute: typeof AppAdminTokoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/pencairan': {
      id: '/_app/admin/pencairan'
      path: '/admin/pencairan'
      fullPath: '/admin/pencairan'
      preLoaderRoute: typeof AppAdminPencairanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/katalog': {
      id: '/_app/admin/katalog'
      path: '/admin/katalog'
      fullPath: '/admin/katalog'
      preLoaderRoute: typeof AppAdminKatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEventRoute: typeof AppEventRoute
  AppFavoritRoute: typeof AppFavoritRoute
  AppKeranjangRoute: typeof AppKeranjangRoute
  AppKoleksiRoute: typeof AppKoleksiRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRiwayatRoute: typeof AppRiwayatRoute
  AppTransaksiRoute: typeof AppTransaksiRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminKatalogRoute: typeof AppAdminKatalogRoute
  AppAdminPencairanRoute: typeof AppAdminPencairanRoute
  AppAdminTokoRoute: typeof AppAdminTokoRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppBukuIdRoute: typeof AppBukuIdRoute
  AppCheckoutIdRoute: typeof AppCheckoutIdRoute
  AppTokoIdRoute: typeof AppTokoIdRoute
  AppTokoBukuRoute: typeof AppTokoBukuRoute
  AppTokoPengembalianRoute: typeof AppTokoPengembalianRoute
  AppTokoRiwayatRoute: typeof AppTokoRiwayatRoute
  AppTokoUploadRoute: typeof AppTokoUploadRoute
  AppTokoVerifikasiRoute: typeof AppTokoVerifikasiRoute
  AppTokoIndexRoute: typeof AppTokoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEventRoute: AppEventRoute,
  AppFavoritRoute: AppFavoritRoute,
  AppKeranjangRoute: AppKeranjangRoute,
  AppKoleksiRoute: AppKoleksiRoute,
  AppProfileRoute: AppProfileRoute,
  AppRiwayatRoute: AppRiwayatRoute,
  AppTransaksiRoute: AppTransaksiRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminKatalogRoute: AppAdminKatalogRoute,
  AppAdminPencairanRoute: AppAdminPencairanRoute,
  AppAdminTokoRoute: AppAdminTokoRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppBukuIdRoute: AppBukuIdRoute,
  AppCheckoutIdRoute: AppCheckoutIdRoute,
  AppTokoIdRoute: AppTokoIdRoute,
  AppTokoBukuRoute: AppTokoBukuRoute,
  AppTokoPengembalianRoute: AppTokoPengembalianRoute,
  AppTokoRiwayatRoute: AppTokoRiwayatRoute,
  AppTokoUploadRoute: AppTokoUploadRoute,
  AppTokoVerifikasiRoute: AppTokoVerifikasiRoute,
  AppTokoIndexRoute: AppTokoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
